name: build

on:
  push:

env:
  OWNER: ${{ github.repository_owner }}
  CONFIGURATION: Release

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Codecov
        continue-on-error: true
        run: bash <(curl -s https://codecov.io/bash)

  build:
    needs: [test]

    runs-on: ubuntu-latest

    env:
      FILE: baget
      IMAGE: ghcr.io/${{ github.repository_owner }}/baget

    steps:
      - uses: actions/checkout@v2.3.4

      - name: docker-config
        uses: renovatebot/internal-tools@v1.2.21
        with:
          command: docker-config

      - name: Build image
        run: docker buildx bake --progress plain test

      - name: Log into registry
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u viceice --password-stdin

      - name: Publish the Docker image
        if: github.ref == 'refs/heads/main'
        run: docker buildx bake build
